services:
  - type: web
    name: webtrader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python .\run\lib\src\controller.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
