services:
  - type: web
    name: webtrader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run.lib.src.controller:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
